version: '3'

services:
  app:
    build:
      context: .
      args:
        - user_uid=${user_uid:-1000}
        - user_gid=${user_gid:-1000}
    volumes:
      - ./app/:/home/user/app/:cached
    ports:
      - 8000:8000
    networks:
      - inner_network
    env_file:
      - .env
    command: python manage.py runserver 0
    restart: always

  postgres:
    image: postgres:12
    expose:
      - 5432
    networks:
      - inner_network
    env_file:
      - .env
    restart: always

networks:
  inner_network:
    driver: bridge
