version: '3'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      args:
        - user_uid=${user_uid:-1000}
        - user_gid=${user_gid:-1000}
    volumes:
      - ./app/:/home/user/app/:cached
    ports:
      - 8080:8080
    networks:
      - inner_network
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0:8080'
    restart: always

  db:
    image: postgres:12
    expose:
      - 5432
    networks:
      - inner_network
    env_file:
      - .env
    restart: always

networks:
  inner_network:
    driver: bridge
