version: '3'

volumes:
  postgres_data: {}
  static_data: {}
  media_data: {}

networks:
  traefik:
    external:
      name: traefik_network

services:
  django: &django
    depends_on:
      - postgres
      - redis
    build: ./app/
    volumes:
      - ./app/:/app/:cached
      - ./app/backups/:/app/backups/
      - static_data:/app/static/
      - media_data:/app/media/
    env_file: .env
    command: ./start
    restart: always

  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file: .env
    restart: always

  nginx:
    depends_on:
      - django
    build: ./nginx/
    expose:
      - 80
    volumes:
      - static_data:/django/static/
      - media_data:/django/media/
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.info_nginx_https.rule=Host("$VIRTUAL_HOST")'
      - 'traefik.http.routers.info_nginx_https.tls.certresolver=httpchallenge_0'
      - 'traefik.http.routers.info_nginx_http.rule=Host("$VIRTUAL_HOST")'
      - 'traefik.http.routers.info_nginx_http.middlewares=redirect_middleware'
      - 'traefik.http.middlewares.redirect_middleware.redirectscheme.scheme=https'
    env_file: .env
    command: nginx -g 'daemon off;'
    restart: always

  redis:
    image: redis:6-buster
    restart: always

  celeryworker:
    <<: *django
    command: celery -A core worker -l info

  celerybeat:
    <<: *django
    command: celery -A core beat -l info

  scrapy:
    <<: *django
    expose:
      - 6800
    command: scrapyd
