# Generated by Django 3.1.4 on 2020-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbrn', models.CharField(max_length=4)),
                ('ogrn', models.CharField(blank=True, max_length=13)),
                ('inn', models.CharField(blank=True, max_length=10)),
                ('trademark', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('federal_subject', models.CharField(blank=True, max_length=200)),
                ('contacts', models.TextField(blank=True)),
                ('licenses', models.JSONField(blank=True, null=True)),
                ('authorized_capital', models.PositiveIntegerField(blank=True, null=True)),
                ('net_profit', models.PositiveIntegerField(blank=True, null=True)),
                ('premiums', models.PositiveIntegerField(blank=True, null=True)),
                ('payouts', models.PositiveIntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('director_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
