# Generated by Django 3.1.4 on 2021-02-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0009_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_self_finparty', models.URLField(blank=True)),
                ('url_bank_banki', models.URLField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('photo', models.URLField(blank=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.bank')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
