# Generated by Django 3.0.11 on 2020-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20201124_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='interest_payment_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='online_opening',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='partial_withdrawal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='partial_withdrawal_description',
            field=models.TextField(blank=True),
        ),
    ]
