# Generated by Django 3.1.4 on 2020-12-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20201202_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='name',
        ),
        migrations.AddField(
            model_name='deposit',
            name='name_base',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='name_full',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='special_contribution_description',
            field=models.TextField(blank=True),
        ),
    ]
