# Generated by Django 3.1.4 on 2020-12-08 06:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20201203_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumercredit',
            name='is_subjected_to_fee',
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='credit_fee',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='credit_fee_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='loan_delivery_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='loan_delivery_order_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='loan_delivery_type_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='loan_security_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='name_base',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='name_full',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='repayment_procedure_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='work_experience_description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='consumercredit',
            name='borrowers_documents',
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='borrowers_documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name='consumercredit',
            name='borrowers_income_documents',
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='borrowers_income_documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name='consumercredit',
            name='credit_insurance',
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='credit_insurance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='consumercredit',
            name='credit_insurance_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='consumercredit',
            name='loan_security',
        ),
        migrations.AddField(
            model_name='consumercredit',
            name='loan_security',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
