# Generated by Django 3.1.4 on 2020-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_auto_20201208_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumercredit',
            name='borrowers_documents_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consumercredit',
            name='credit_fee_description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
