# Generated by Django 3.1.4 on 2021-01-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_auto_20201208_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banki_id', models.CharField(blank=True, max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('bank_url', models.URLField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('metro', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('region_name', models.CharField(blank=True, max_length=200)),
                ('region_name_full', models.CharField(blank=True, max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='banks.bank')),
            ],
        ),
    ]
