# Generated by Django 3.1.4 on 2021-01-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banki_url', models.URLField(blank=True)),
                ('banki_bank_url', models.URLField(blank=True)),
                ('net_assets', models.BigIntegerField(null=True)),
                ('net_profit', models.BigIntegerField(null=True)),
                ('equity', models.BigIntegerField(null=True)),
                ('credit_portfolio', models.BigIntegerField(null=True)),
                ('npls', models.BigIntegerField(null=True)),
                ('private_deposits', models.BigIntegerField(null=True)),
                ('investment_in_securities', models.BigIntegerField(null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='banks.bank')),
            ],
        ),
    ]
