# Generated by Django 3.1.4 on 2021-02-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banki_url', models.URLField(blank=True)),
                ('banki_bank_url', models.URLField(blank=True)),
                ('net_assets', models.JSONField(blank=True, help_text='Активы нетто (тыс. руб. по месяцам)', null=True)),
                ('net_profit', models.JSONField(blank=True, help_text='Чистая прибыль (тыс. руб. по месяцам)', null=True)),
                ('equity', models.JSONField(blank=True, help_text='Капитал (по форме 123) (тыс. руб. по месяцам)', null=True)),
                ('credit_portfolio', models.JSONField(blank=True, help_text='Кредитный портфель (тыс. руб. по месяцам)', null=True)),
                ('npls', models.JSONField(blank=True, help_text='Просроченная задолженность в кредитном портфеле (тыс. руб. по месяцам)', null=True)),
                ('private_deposits', models.JSONField(blank=True, help_text='Вклады физических лиц (тыс. руб. по месяцам)', null=True)),
                ('investment_in_securities', models.JSONField(blank=True, help_text='Вложения в ценные бумаги (тыс. руб. по месяцам)', null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
