# Generated by Django 3.1.4 on 2021-02-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='banki_bank_url',
            new_name='url_bank_banki',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='banki_url',
            new_name='url_self_banki',
        ),
        migrations.AddField(
            model_name='rating',
            name='funds_held_by_businesses_and_institutions',
            field=models.JSONField(blank=True, help_text='Средства предприятий и организаций', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='household_credits',
            field=models.JSONField(blank=True, help_text='Кредиты физическим лицам', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='interbank_loans_raised',
            field=models.JSONField(blank=True, help_text='Привлеченные МБК', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='level_of_ensuring_loan_portfolio_by_pledge_of_property',
            field=models.JSONField(blank=True, help_text='Уровень обеспечения кредитного портфеля залогом имущества', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='level_of_provisioning_loan_portfolio',
            field=models.JSONField(blank=True, help_text='Уровень резервирования по кредитному портфелю', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='loans_extended_to_businesses_and_institutions',
            field=models.JSONField(blank=True, help_text='Кредиты предприятиям и организациям', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='loro_accounts',
            field=models.JSONField(blank=True, help_text='ЛОРО-счета', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='n1',
            field=models.JSONField(blank=True, help_text='Н1', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='n2',
            field=models.JSONField(blank=True, help_text='Н2', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='n3',
            field=models.JSONField(blank=True, help_text='Н3', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='overdue_debts_to_loans_portfolio',
            field=models.JSONField(blank=True, help_text='Уровень просроченной задолженности по кредитному портфелю', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='promissory_notes_and_bonds_issued',
            field=models.JSONField(blank=True, help_text='Выпущенные облигации и векселя', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='return_on_assets',
            field=models.JSONField(blank=True, help_text='Рентабельность активов-нетто', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='return_on_equity',
            field=models.JSONField(blank=True, help_text='Рентабельность капитала', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='credit_portfolio',
            field=models.JSONField(blank=True, help_text='Кредитный портфель', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='equity',
            field=models.JSONField(blank=True, help_text='Капитал (по форме 123)', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='investment_in_securities',
            field=models.JSONField(blank=True, help_text='Вложения в ценные бумаги', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='net_assets',
            field=models.JSONField(blank=True, help_text='Активы нетто', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='net_profit',
            field=models.JSONField(blank=True, help_text='Чистая прибыль', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='npls',
            field=models.JSONField(blank=True, help_text='Просроченная задолженность в кредитном портфеле', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='private_deposits',
            field=models.JSONField(blank=True, help_text='Вклады физических лиц', null=True),
        ),
    ]
