# Generated by Django 3.1.4 on 2021-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItunesApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('screenshots', models.JSONField(blank=True, null=True)),
                ('version_history', models.JSONField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('compatibility', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
