# Generated by Django 3.0.10 on 2020-10-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-category']},
        ),
    ]
