# Generated by Django 3.0.11 on 2020-11-29 21:04

from urllib.parse import unquote

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def driver_to_spider(apps, schema_editor):
    Table = apps.get_model('tables', 'Table')
    for table in Table.objects.all():
        table.spider = table.driver.scraper
        if table.driver_args:
            table.spider_kwargs = {'table_name': table.driver_args[0]}
        table.save()


def normalize_urls(apps, schema_editor):
    Table = apps.get_model('tables', 'Table')
    for table in Table.objects.all():
        table.url = unquote(table.url)
        table.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20201124_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='spider',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='table',
            name='spider_kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(driver_to_spider),
        migrations.RemoveField(
            model_name='table',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='table',
            name='driver_args',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.RunPython(normalize_urls),
    ]
