# Generated by Django 3.1.4 on 2020-12-17 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\w{12}$')])),
                ('name', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_dynamic', models.JSONField(blank=True, null=True)),
                ('dividend_history', models.JSONField(blank=True, null=True)),
                ('seo_quote', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
