# Generated by Django 3.1.4 on 2020-12-18 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\w{12}$')])),
                ('name', models.TextField(blank=True)),
                ('issuer', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('risk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maturity_yield', models.FloatField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('offer_yield', models.FloatField(blank=True, null=True)),
                ('offer_date', models.DateTimeField(blank=True, null=True)),
                ('coupon_yield', models.FloatField(blank=True, null=True)),
                ('coupon_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
