# Generated by Django 3.1.4 on 2020-12-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_bond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='issuer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bond',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
