# Generated by Django 3.1.4 on 2020-12-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_iia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('filter', models.CharField(blank=True, max_length=200)),
                ('investment_min', models.PositiveIntegerField(blank=True, null=True)),
                ('yield_type', models.CharField(blank=True, max_length=200)),
                ('yield_value', models.FloatField(blank=True, null=True)),
                ('yield_block', models.JSONField(blank=True, null=True)),
                ('fees', models.JSONField(blank=True, null=True)),
                ('docs', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
